apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::973531348166:role/nurigo-testbed-ng-role-20240510002759685800000006"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - groups:
      - system:bootstrappers
      - system:nodes
      ## If you intend to run Windows workloads, the kube-proxy group should be specified.
      # For more information, see https://github.com/aws/karpenter/issues/5099.
      # - eks:kube-proxy-windows
      rolearn: arn:aws:iam::973531348166:role/KarpenterNodeRole-apple-testbed-eksCluster
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
