apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/nurigo/devops.git
      revision: main
      files:
      - path: argocd/addons/envs/dev/nurigo-istio-base.yaml

  template:
    metadata:
      name: 'istio-{{ app_name }}-dev'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/nurigo/devops.git
        targetRevision: HEAD
        path: 'helm-chart/istio/{{ app_name }}'
        helm:
          values: |-
            defaultRevision=default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
