apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istiod
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/nurigo/devops.git
      revision: main
      files:
      - path: argocd/addons/envs/dev/nurigo-istio-daemon.yaml

  template:
    metadata:
      name: 'istio-{{ app_name }}-dev'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/nurigo/devops.git
        targetRevision: HEAD
        path: 'helm-chart/istio/{{ app_name }}'
        helm:
          # values: |-
          #   defaults:
          #     meshConfig
          #       ingressSelector: istio-ingress
          #       ingressService: istio-ingress
          #     pilot:
          #       env: K8S_INGRESS_NS=istio-ingress
          valueFiles:
          - "values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
